services:
  - type: cron
    name: world-cup-bot
    env: python
    plan: free
    region: oregon
    schedule: "*/120 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./.render-start.sh"
    envVars:
      - key: API_KEY
        sync: false
      - key: GOOGLE_CHAT_SPACE_NAME
        sync: false
      - key: KEYS_ENV
        sync: false
      - key: TOKEN_JSON
        sync: false
      - key: CLIENT_SECRET_JSON
        sync: false
